### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by perbnielsen** [OmniSharp/omnisharp-atom#325] opened 2015-05-21 19:42 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

```
At /Users/perb/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:112

TypeError: Cannot read property 'getBoundingClientRect' of undefined
  at GoToDefinition.pixelPositionFromMouseEvent (/Users/perb/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:112:77)
  at GoToDefinition.underlineIfNavigable (/Users/perb/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:78:28)
  at /Users/perb/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:50:79

```

### Commands

```
     -0:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:09.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:05.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:indent (atom-text-editor.editor.is-focused)
  7x -0:04.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
linter, v0.12.6
omnisharp-atom, v0.6.1

# Dev
No dev packages
```

**Comment by perbnielsen** [comment] 2015-05-21 21:31
I found a way to reproduce it every time:

1.) Open two .cs files
2.) Trigger a lot of autocompletions
3.) Close both files quickly.

I don't see any completion suggestions from omnisharp, at all, is it suppose to work on OS X at the moment? I had a version of Atom and Omnisharp-atom that worked at couple of weeks ago, but at some point an update broke it and it has not worked since.

I have Mono version 4.0.0 and have also tried with version 3.12.1.

**Comment by nosami** [comment] 2015-05-21 21:40
It is supposed to work on OSX, yes :)
![atomdemo](https://cloud.githubusercontent.com/assets/667194/7759547/41d2dba6-000a-11e5-90bf-ce74d1156438.gif)

Mono v4.0.0 seems quite unstable though. 3.12 is better.

**Comment by perbnielsen** [comment] 2015-05-21 21:41
I tried Visual Studio Code, where autocompletion works, and the output in their "OnmiSharp Log" is almost identical to the "Omnisharp Output" from Atom, when I open a minimal C# project. Atom does throw an exception that VSC does not throw. 

I also see the following when I open a .cs file and try to use Omnisharp, but as mentioned, there are no completion suggestions or other signs that it worked.
/updatebuffer: 200 158ms
/codecheck: 200 14ms
/autocomplete: 200 12ms

I get the following in the console when I open a minimal c# project:

Omnisharp server running on port '2000' at location '/Users/perb/Desktop/Empty' on host 12013.
The specified runtime path 'default' does not exist. Searched locations /Users/perb/.dnx/runtimes/dnx-mono.default
/Users/perb/.dnx/runtimes/kre-mono.default
/Users/perb/.dnx/packages/KRE-Mono.default
/Users/perb/.k/runtimes/dnx-mono.default
/Users/perb/.k/runtimes/kre-mono.default
/Users/perb/.k/packages/KRE-Mono.default
/Users/perb/.kre/runtimes/dnx-mono.default
/Users/perb/.kre/runtimes/kre-mono.default
/Users/perb/.kre/packages/KRE-Mono.default.
Visit https://github.com/aspnet/Home/tree/glennc/readmelove for an installation guide.
Scanning '/Users/perb/Desktop/Empty' for ASP.NET 5 projects
No project.json based projects found
Detecting projects in '/Users/perb/Desktop/Empty/Empty.sln'.
Loading project from '/Users/perb/Desktop/Empty/Empty/Empty.csproj'.
Failed to process project file '/Users/perb/Desktop/Empty/Empty/Empty.csproj'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in :0 
  at System.Collections.Generic.Dictionary`2[System.String,Microsoft.Build.BuildEngine.BuildProperty].get_Item (System.String key) [0x00000] in :0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (OmniSharp.Options.MSBuildOptions options, ILogger logger, System.String solutionDirectory, System.String projectFilePath, ICollection`1 diagnostics) [0x00000] in :0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject (System.String projectFilePath) [0x00000] in :0
Error
MsBuildProjectDiagnostics
Could not find any CSX files
Solution has finished loading
Detecting CSX files in '/Users/perb/Desktop/Empty'.
started

**Comment by nosami** [comment] 2015-05-21 21:42
Ah... so the server bailed on your solution. I'll see what I can do.

**Comment by nosami** [comment] 2015-05-21 21:49
Any chance you can share your solution?

**Comment by perbnielsen** [comment] 2015-05-21 21:57
Sure - this is the minimal project I was trying it on. https://dl.dropboxusercontent.com/u/19866522/Empty.zip


I just tried with the WebApplication as in the example you posted above and I don't get the KeyNotFoundException, but I still don't get any completion suggestions. I have attached the output when I open below. I also do not get the popup name "Package Restore Started" but my flame icon does turn green.

I would love to use Atom for Unity development, but I also get the same Exception when I open a project from Unity.

 I have attached the output when I open the WebApplication below.
Omnisharp server running on port '2000' at location '/Users/perb/Desktop/TestingAtom/WebApplication' on host 12175.
Scanning '/Users/perb/Desktop/TestingAtom/WebApplication' for ASP.NET 5 projects
Solution has finished loading
Found project '/Users/perb/Desktop/TestingAtom/WebApplication/project.json'.
No default runtime found
Error
The specified runtime path 'default' does not exist. Searched locations /Users/perb/.dnx/runtimes/dnx-mono.default
/Users/perb/.dnx/runtimes/kre-mono.default
/Users/perb/.dnx/packages/KRE-Mono.default
/Users/perb/.k/runtimes/dnx-mono.default
/Users/perb/.k/runtimes/kre-mono.default
/Users/perb/.k/packages/KRE-Mono.default
/Users/perb/.kre/runtimes/dnx-mono.default
/Users/perb/.kre/runtimes/kre-mono.default
/Users/perb/.kre/packages/KRE-Mono.default.
Visit https://github.com/aspnet/Home/tree/glennc/readmelove for an installation guide.
No solution files found in '/Users/perb/Desktop/TestingAtom/WebApplication'
Detecting CSX files in '/Users/perb/Desktop/TestingAtom/WebApplication'.
Could not find any CSX files
started
/updatebuffer: 200 135ms
/codecheck: 200 23ms
/gotodefinition: 200 4ms
/typelookup: 200 5ms

**Comment by nosami** [comment] 2015-05-21 22:01
This one is a different problem. You don't have dnvm installed. You need it for aspnet5 apps. Follow the guidelines here https://github.com/OmniSharp/omnisharp-atom/issues/325

**Comment by perbnielsen** [comment] 2015-05-21 22:22
Thank you. Installing dnvm worked, now I get completion on the WebApplication project. (I think your link is wrong though, as it seems to link back to this Issue.) Still not on the "Empty" project i linked above or the Unity projects I would love to use it on.

**Comment by nosami** [comment] 2015-05-21 22:27
I fixed the link after posting ;) I'm investigating why this solution doesn't work as we speak.

**Comment by fishg** [comment] 2015-05-22 07:41
Not work on my Unity3D project,this is omnisharp output:

Errors & WarningsFindBuild outputOmnisharp output
Omnisharp server running on port '2000' at location '/Users/fishg/data/JDK/hero' on host 12968.
Using runtime '/Users/fishg/.dnx/runtimes/dnx-mono.1.0.0-beta4'.
Scanning '/Users/fishg/data/JDK/hero' for ASP.NET 5 projects
No project.json based projects found
Detecting projects in '/Users/fishg/data/JDK/hero/hero-csharp.sln'.
Loading project from '/Users/fishg/data/JDK/hero/Assembly-CSharp-vs.csproj'.
Failed to process project file '/Users/fishg/data/JDK/hero/Assembly-CSharp-vs.csproj'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in :0 
  at System.Collections.Generic.Dictionary`2[System.String,Microsoft.Build.BuildEngine.BuildProperty].get_Item (System.String key) [0x00000] in :0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (OmniSharp.Options.MSBuildOptions options, ILogger logger, System.String solutionDirectory, System.String projectFilePath, ICollection`1 diagnostics) [0x00000] in :0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject (System.String projectFilePath) [0x00000] in :0
Error
MsBuildProjectDiagnostics
Loading project from '/Users/fishg/data/JDK/hero/Assembly-CSharp-Editor-vs.csproj'.
The member `AstarPath.active' does not hide an inherited member. The new keyword is not required
The member `AstarPath.active' does not hide an inherited member. The new keyword is not required
The member `Pathfinding.DebugUtility.active' does not hide an inherited member. The new keyword is not required
The member `Pathfinding.DebugUtility.active' does not hide an inherited member. The new keyword is not required
`RoleAI.collider2D' hides inherited member `UnityEngine.Component.collider2D'. Use the new keyword if hiding was intended
`RoleAI.collider2D' hides inherited member `UnityEngine.Component.collider2D'. Use the new keyword if hiding was intended
`AttackTimeFence.IsPass(float, bool)' hides inherited member `TimeFence.IsPass(float, bool)'. Use the new keyword if hiding was intended
`AttackTimeFence.IsPass(float, bool)' hides inherited member `TimeFence.IsPass(float, bool)'. Use the new keyword if hiding was intended
`ReleasableGoodsUseEffectBaseBehaviour.tag' hides inherited member `UnityEngine.Component.tag'. Use the new keyword if hiding was intended
`ReleasableGoodsUseEffectBaseBehaviour.tag' hides inherited member `UnityEngine.Component.tag'. Use the new keyword if hiding was intended
`KillingTask.Initialize()' hides inherited member `RewardTaskBase.Initialize()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`KillingTask.Initialize()' hides inherited member `RewardTaskBase.Initialize()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`KillingTask.TimeOut()' hides inherited member `RewardTaskBase.TimeOut()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`KillingTask.TimeOut()' hides inherited member `RewardTaskBase.TimeOut()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`KillingTask.TaskFinished()' hides inherited member `RewardTaskBase.TaskFinished()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`KillingTask.TaskFinished()' hides inherited member `RewardTaskBase.TaskFinished()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword
`FourthStageThrowSkill.OnPrepareAnimationFinished()' hides inherited member `MultiThrowSkill.OnPrepareAnimationFinished()'. Use the new keyword if hiding was intended
`FourthStageThrowSkill.OnPrepareAnimationFinished()' hides inherited member `MultiThrowSkill.OnPrepareAnimationFinished()'. Use the new keyword if hiding was intended
The variable `payload' is assigned but its value is never used
The variable `payload' is assigned but its value is never used
The variable `storeAssetsJSON' is assigned but its value is never used
The variable `storeAssetsJSON' is assigned but its value is never used
The variable `viJSON' is assigned but its value is never used
The variable `viJSON' is assigned but its value is never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
Unreachable code detected
Unreachable code detected
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `e' is declared but never used
The variable `cameraEffect' is assigned but its value is never used
The variable `cameraEffect' is assigned but its value is never used
The variable `tr_helpAttack' is assigned but its value is never used
The variable `tr_helpAttack' is assigned but its value is never used
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
The variable `totalNum' is assigned but its value is never used
The variable `totalNum' is assigned but its value is never used
The variable `isAddBagSuccess' is assigned but its value is never used
The variable `isAddBagSuccess' is assigned but its value is never used
The variable `isAddStoreSuccess' is assigned but its value is never used
The variable `isAddStoreSuccess' is assigned but its value is never used
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
The variable `oldEquipment' is assigned but its value is never used
The variable `oldEquipment' is assigned but its value is never used
The result of comparing value type `CameraType' with null is always `false'
The result of comparing value type `CameraType' with null is always `false'
Unreachable code detected
Unreachable code detected
The result of comparing value type `UnityEngine.Vector3' with null is always `false'
The result of comparing value type `UnityEngine.Vector3' with null is always `false'
The result of comparing value type `UnityEngine.Vector3' with null is always `false'
The result of comparing value type `UnityEngine.Vector3' with null is always `false'
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
The result of comparing value type `UnityEngine.Vector3' with null is always `true'
The result of comparing value type `UnityEngine.Vector3' with null is always `true'
Unreachable expression code detected
Unreachable expression code detected
The variable `displayProgress' is assigned but its value is never used
The variable `displayProgress' is assigned but its value is never used
The variable `toProgress' is assigned but its value is never used
The variable `toProgress' is assigned but its value is never used
The variable `coreVO' is assigned but its value is never used
The variable `coreVO' is assigned but its value is never used
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
The variable `aDirection' is assigned but its value is never used
The variable `aDirection' is assigned but its value is never used
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
Unreachable code detected
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
Unreachable code detected
Unreachable code detected
The variable `leader' is assigned but its value is never used
The variable `leader' is assigned but its value is never used
The variable `handRect' is assigned but its value is never used
The variable `handRect' is assigned but its value is never used
The variable `leader' is assigned but its value is never used
The variable `leader' is assigned but its value is never used
The variable `handRect' is assigned but its value is never used
The variable `handRect' is assigned but its value is never used
The variable `ArrowRect' is assigned but its value is never used
The variable `ArrowRect' is assigned but its value is never used
The variable `cf' is assigned but its value is never used
The variable `cf' is assigned but its value is never used
The variable `gcf' is assigned but its value is never used
The variable `gcf' is assigned but its value is never used
The variable `i' is assigned but its value is never used
The variable `i' is assigned but its value is never used
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
The variable `checker' is assigned but its value is never used
The variable `checker' is assigned but its value is never used
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
The variable `targetRoleAI' is assigned but its value is never used
The variable `targetRoleAI' is assigned but its value is never used
Unreachable code detected
Unreachable code detected
The variable `mgr' is assigned but its value is never used
The variable `mgr' is assigned but its value is never used
The variable `dict' is assigned but its value is never used
The variable `dict' is assigned but its value is never used
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
`RoleAI.GetStateContext()' is obsolete: `GetStateContext method is deprecated, you should not get a context outside a AI'
The variable `t2' is assigned but its value is never used
The variable `t2' is assigned but its value is never used
`UnityEngine.MeshCollider.smoothSphereCollisions' is obsolete: `Configuring smooth sphere collisions is no longer needed. PhysX3 has a better behaviour in place.'
`UnityEngine.MeshCollider.smoothSphereCollisions' is obsolete: `Configuring smooth sphere collisions is no longer needed. PhysX3 has a better behaviour in place.'
The private field `JDK.Payment.Services.AppStorePayService.handler' is assigned but its value is never used
The private field `JDK.Payment.Services.AppStorePayService.handler' is assigned but its value is never used
The private field `AdsManager.channel' is assigned but its value is never used
The private field `AdsManager.channel' is assigned but its value is never used
The private field `WaitForAnimation.first' is assigned but its value is never used
The private field `WaitForAnimation.first' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.channel' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.channel' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.co' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.co' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.company' is assigned but its value is never used
The private field `JDK.Payment.Services.JDKOfflinePayService.company' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.channel' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.channel' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.offerID' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.offerID' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.gameId' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.gameId' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.gameName' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.gameName' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.co' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.co' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.company' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentOfflinePayService.company' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentPayService.co' is assigned but its value is never used
The private field `JDK.Payment.Services.TencentPayService.co' is assigned but its value is never used
Field `JDK.QQService.successCallBack' is never assigned to, and will always have its default value `null'
Field `JDK.QQService.successCallBack' is never assigned to, and will always have its default value `null'
Field `JDK.QQService.failCallBack' is never assigned to, and will always have its default value `null'
Field `JDK.QQService.failCallBack' is never assigned to, and will always have its default value `null'
The private field `CameraFollowTest.hasChangeLeader' is assigned but its value is never used
The private field `CameraFollowTest.hasChangeLeader' is assigned but its value is never used
The private field `PlayerFollowAgent.navAgent' is assigned but its value is never used
The private field `PlayerFollowAgent.navAgent' is assigned but its value is never used
The private field `AISystem.BehaviourState.PathFindState.ctx' is assigned but its value is never used
The private field `AISystem.BehaviourState.PathFindState.ctx' is assigned but its value is never used
The private field `BlindState.detectEnemyTimeFence' is assigned but its value is never used
The private field `BlindState.detectEnemyTimeFence' is assigned but its value is never used
The private field `BlindState.runOnce' is assigned but its value is never used
The private field `BlindState.runOnce' is assigned but its value is never used
The private field `DeadState.canExit' is assigned but its value is never used
The private field `DeadState.canExit' is assigned but its value is never used
The private field `DizzinessState.detectEnemyTimeFence' is assigned but its value is never used
The private field `DizzinessState.detectEnemyTimeFence' is assigned but its value is never used
The private field `DizzinessState.runOnce' is assigned but its value is never used
The private field `DizzinessState.runOnce' is assigned but its value is never used
The private field `FreezeState.detectEnemyTimeFence' is assigned but its value is never used
The private field `FreezeState.detectEnemyTimeFence' is assigned but its value is never used
The private field `FreezeState.runOnce' is assigned but its value is never used
The private field `FreezeState.runOnce' is assigned but its value is never used
The private field `GobackState.isGoBacking' is assigned but its value is never used
The private field `GobackState.isGoBacking' is assigned but its value is never used
The private field `HurtState.hurtTime' is assigned but its value is never used
The private field `HurtState.hurtTime' is assigned but its value is never used
The private field `PickObjectState._reachDistance' is assigned but its value is never used
The private field `PickObjectState._reachDistance' is assigned but its value is never used
The private field `RepulsedState.fromPos' is assigned but its value is never used
The private field `RepulsedState.fromPos' is assigned but its value is never used
Field `UserGoodsManager.SkillData' is never assigned to, and will always have its default value `null'
Field `UserGoodsManager.SkillData' is never assigned to, and will always have its default value `null'
The private field `MapPticalParallaxController.interval' is assigned but its value is never used
The private field `MapPticalParallaxController.interval' is assigned but its value is never used
The private field `CharacterEquipmentController.preEquipmentType' is assigned but its value is never used
The private field `CharacterEquipmentController.preEquipmentType' is assigned but its value is never used
The private field `CharacterEquipmentController.getedChilds' is assigned but its value is never used
The private field `CharacterEquipmentController.getedChilds' is assigned but its value is never used
The private field `CharacterEquipmentInfo.equipmentList' is assigned but its value is never used
The private field `CharacterEquipmentInfo.equipmentList' is assigned but its value is never used
The private field `ReleasableGoodsUseEffectBaseBehaviour.preColor' is assigned but its value is never used
The private field `ReleasableGoodsUseEffectBaseBehaviour.preColor' is assigned but its value is never used
The private field `BustConversationController.ConversationCount' is assigned but its value is never used
The private field `BustConversationController.ConversationCount' is assigned but its value is never used
The private field `EnemyVO._skillId' is assigned but its value is never used
The private field `EnemyVO._skillId' is assigned but its value is never used
The private field `EnemyVO._attackSkillId' is assigned but its value is never used
The private field `EnemyVO._attackSkillId' is assigned but its value is never used
The private field `SceneController.SCENE_CONTROLLER_NAME' is assigned but its value is never used
The private field `SceneController.SCENE_CONTROLLER_NAME' is assigned but its value is never used
The private field `EpisodeMoveCommand.moveSpeed' is assigned but its value is never used
The private field `EpisodeMoveCommand.moveSpeed' is assigned but its value is never used
The private field `GuideManager._isInitFinished' is assigned but its value is never used
The private field `GuideManager._isInitFinished' is assigned but its value is never used
The private field `MedicineBottleGuideEffect.guideCameraEffect' is assigned but its value is never used
The private field `MedicineBottleGuideEffect.guideCameraEffect' is assigned but its value is never used
The private field `MainBaseModel.udm' is assigned but its value is never used
The private field `MainBaseModel.udm' is assigned but its value is never used
The private field `StoryMask.timePast' is assigned but its value is never used
The private field `StoryMask.timePast' is assigned but its value is never used
The private field `BornInfo.direction' is assigned but its value is never used
The private field `BornInfo.direction' is assigned but its value is never used
The private field `ElfAgent.isArrived' is assigned but its value is never used
The private field `ElfAgent.isArrived' is assigned but its value is never used
The private field `RoleHighlighter.tr' is assigned but its value is never used
The private field `RoleHighlighter.tr' is assigned but its value is never used
The private field `RoleHighlighterStateNormal.timeFence' is assigned but its value is never used
The private field `RoleHighlighterStateNormal.timeFence' is assigned but its value is never used
The private field `RoleHighlighterStateNormal.runOnce' is assigned but its value is never used
The private field `RoleHighlighterStateNormal.runOnce' is assigned but its value is never used
The private field `RoleHurtEffectPlayer.tr' is assigned but its value is never used
The private field `RoleHurtEffectPlayer.tr' is assigned but its value is never used
The private field `SimpleCharacterController2D._slopeLimitTangent' is assigned but its value is never used
The private field `SimpleCharacterController2D._slopeLimitTangent' is assigned but its value is never used
The private field `SimpleCharacterController2D._isGoingUpSlope' is assigned but its value is never used
The private field `SimpleCharacterController2D._isGoingUpSlope' is assigned but its value is never used
The private field `MultiSideSkill.moveDeltas' is assigned but its value is never used
The private field `MultiSideSkill.moveDeltas' is assigned but its value is never used
The private field `MultiSideSkill.am' is assigned but its value is never used
The private field `MultiSideSkill.am' is assigned but its value is never used
The private field `MultiSideSkill.sr' is assigned but its value is never used
The private field `MultiSideSkill.sr' is assigned but its value is never used
The private field `MultiThrowSkill.moveDeltas' is assigned but its value is never used
The private field `MultiThrowSkill.moveDeltas' is assigned but its value is never used
The private field `ThreeDirectionWithChildAttack.hasBeginThrow' is assigned but its value is never used
The private field `ThreeDirectionWithChildAttack.hasBeginThrow' is assigned but its value is never used
The private field `TabControl.panelContainer' is assigned but its value is never used
The private field `TabControl.panelContainer' is assigned but its value is never used
The private field `TabControl.tabContainer' is assigned but its value is never used
The private field `TabControl.tabContainer' is assigned but its value is never used
The private field `TabControl.tabPrefab' is assigned but its value is never used
The private field `TabControl.tabPrefab' is assigned but its value is never used
The private field `TabControl.panelPrefab' is assigned but its value is never used
The private field `TabControl.panelPrefab' is assigned but its value is never used
Field `TavernUIManager.heroCellCtrlDict' is never assigned to, and will always have its default value `null'
Field `TavernUIManager.heroCellCtrlDict' is never assigned to, and will always have its default value `null'
Failed to process project file '/Users/fishg/data/JDK/hero/Assembly-CSharp-Editor-vs.csproj'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in :0 
  at System.Collections.Generic.Dictionary`2[System.String,Microsoft.Build.BuildEngine.BuildProperty].get_Item (System.String key) [0x00000] in :0 
  at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create (OmniSharp.Options.MSBuildOptions options, ILogger logger, System.String solutionDirectory, System.String projectFilePath, ICollection`1 diagnostics) [0x00000] in :0 
  at OmniSharp.MSBuild.MSBuildProjectSystem.CreateProject (System.String projectFilePath) [0x00000] in :0
Error
MsBuildProjectDiagnostics
Detecting CSX files in '/Users/fishg/data/JDK/hero'.
Could not find any CSX files
Solution has finished loading
started
/updatebuffer: 200 118ms
/codecheck: 200 7ms
/typelookup: 200 6ms
/codecheck: 200 2ms
/typelookup: 200 1ms
/autocomplete: 200 8ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/updatebuffer: 200 0ms
/codecheck: 200 0ms
/updatebuffer: 200 3ms
/codecheck: 200 0ms
/autocomplete: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/codecheck: 200 0ms
/updatebuffer: 200 0ms
/codecheck: 200 0ms
/updatebuffer: 200 0ms
/codecheck: 200 0ms
/codecheck: 200 1ms
/codecheck: 200 0ms
/codecheck: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/autocomplete: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/autocomplete: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/autocomplete: 200 1ms
/codecheck: 200 0ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/codecheck: 200 1ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/updatebuffer: 200 1ms
/codecheck: 200 0ms
/codecheck: 200 0ms
00Assets/Scripts/Shop/ShopEquipmentsDataManager.cs77,7
UTF-8C#master+1, -11 update!

**Comment by nosami** [comment] 2015-05-22 07:43
@fishg that's because you don't have the fix yet :)

**Comment by ladislaolainez** [comment] 2015-05-22 08:15
Same here guys, and I want to use for Unity3D too. A simple, blank project doesn't work either. No autocomplete, no "Go to Definition" etc. Just letting you know you are not alone ;-)

If there is something I can do to help you @nosami let me know. BTW using Omnisharp in Sublime Text is working for me at this moment, but I would love to use Atom.

**Comment by nosami** [comment] 2015-05-22 08:17
Well... it works fine for me with the update to omnisharp-roslyn. Need to wait for that fix https://github.com/OmniSharp/omnisharp-roslyn/issues/228 to be approved and then I can bundle it with omnisharp-atom.

**Comment by nosami** [comment] 2015-05-22 08:21
If you don't want to wait for the fix, you could fudge it by adding the LangVersion to your csproj file like this :- https://github.com/search?utf8=%E2%9C%93&q=LangVersion+extension%3Acsproj&type=Code&ref=searchresults

**Comment by ladislaolainez** [comment] 2015-05-22 08:33
With the latest version (0.6.4) is working for blank projects, but not for Unity projects. I will check that link. Thanks @nosami ;-)
![screen shot 2015-05-22 at 10 32 37](https://cloud.githubusercontent.com/assets/11684106/7766865/e976c4ea-006d-11e5-93e3-8377dab21ad0.png)

**Comment by ladislaolainez** [comment] 2015-05-22 08:42
And using the link you posted Unity projects work too. Thanks @nosami, you rock. I added `<LangVersion>default</LangVersion>` in all `<PropertyGroup>` of each `.csproj` of the Unity project and now it works like a charm.
![screen shot 2015-05-22 at 10 40 11](https://cloud.githubusercontent.com/assets/11684106/7767003/315d0f66-006f-11e5-8b56-696e9d3fe76e.png)

**Closed** 2015-05-22 09:06 UTC

**Comment by perbnielsen** [comment] 2015-05-22 09:51
This is great news, I can confirm that adding "<LangVersion>default</LangVersion>" to the .csproj works, and I am looking forward to not even having to do that. Great work!

But I actually don't think this solved the original problem. At least I am still getting the 'getBoundingClientRect' issue on version 0.6.4, even with everything else working.

I guess I hijacked my own bug report :-).

I can still reproduce it by:
1.) Opening the "Empty" project I linked above (with the "<LangVersion>default</LangVersion>" added).
2.) Open AssemblyInfo.cs and Program.cs
3.) Click somewhere that will fire a codelookup
4.) _Immediately_ after clicking, close both files quickly.

**Comment by nosami** [comment] 2015-05-22 11:14
Unity projects should be fixed in v0.6.5.

Haven't been able to reproduce the tooltip issue yet.

**Comment by david-driscoll** [comment] 2015-05-22 11:43
@perbnielsen @nosami If it has to do with editor windows closing, then it sounds like the request is in-flight, and the editor closes before the request finishes.

We should be able to guard against this, in the tooltip calling code.  Ideally we should be able to automatically guard against this in the client-manager... I can look into that part soon.

**Comment by nosami** [comment] 2015-05-22 16:58
Yeah... sounds like this needs to be abstracted away though. It's probably an issue for all the commands, not just tooltips.

**Comment by david-driscoll** [comment] 2015-05-22 17:09
Yeah we need a way to cancel the in flight request if the editor is destroyed.
