### ISSUE TITLE
Uncaught TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by nteague22** [OmniSharp/omnisharp-atom#503] opened 2015-09-09 17:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.6

### Stack Trace

Uncaught TypeError: Cannot read property 'state' of undefined

```
At C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71

TypeError: Cannot read property 'state' of undefined
    at C:\Users\nteague\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:301:59
    at tryCatcher (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at InnerObserver.onNext (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2010:45)
    at InnerObserver.tryCatcher (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at InnerObserver.onNext (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5094:29)
    at InnerObserver.tryCatcher (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at InnerObserver.onNext (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4792:14)
    at AsyncSubject.subscribe [as _subscribe] (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5377:18)
    at AsyncSubject.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
    at MapObservable.subscribeCore (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4777:26)
    at MapObservable.tryCatcher (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at setDisposable (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1943:46)
    at MapObservable.subscribe [as _subscribe] (C:\Users\nteague\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1957:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "c:\\usr\\git"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
json-schema, v0.1.13
linter, v1.5.1
omnisharp-atom, v0.24.6

# Dev
No dev packages
```

**Comment by david-driscoll** [comment] 2015-09-24 15:37
Is this still an issue with the latest version?

There has been some refactoring around that line, that may have cleared this issue up.

**Comment by david-driscoll** [comment] 2015-09-25 03:02
Closing for now, let us know if you still see this issue!

**Closed by david-driscoll** 2015-09-25 03:02 UTC

**Comment by nteague22** [comment] 2015-10-03 17:34
I'm sorry I did not see this notification, I was working in  Atom the past three days and did not see the issue

**Comment by lukas-123** [comment] 2016-04-11 09:52
This issue seems to be occuring again.

[Enter steps to reproduce below:]

1. Open project with solution generated by Unity
2. Restart server (solution is not automatically detected)

**Atom Version**: 1.5.3
**System**: Debian GNU/Linux
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.28.0


### Stack Trace

Uncaught TypeError: Cannot read property 'state' of undefined

```
At /home/lukas/.atom/packages/omnisharp-atom/lib/atom/solution-information.js:65

TypeError: Cannot read property 'state' of undefined
    at atom-workspace.<anonymous> (/home/lukas/.atom/packages/omnisharp-atom/lib/atom/solution-information.js:65:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:08.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:05.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 omnisharp-atom:restart-server (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "autoAdjustTreeView": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
atom-yeoman, v0.3.15
color-picker, v2.1.1
file-icons, v1.7.1
json-schema, v0.1.15
linter, v1.11.4
linter-js-standard, v3.2.1
minimap, v4.21.0
omnisharp-atom, v0.28.0
standard-formatter, v2.0.0

# Dev
No dev packages
```

**Comment by lukas-123** [comment] 2016-04-11 10:08
I just updated Atom and now I get the same error as in #696 .

**Comment by liefswanson** [comment] 2016-11-27 00:04
I am having this problem too, but I think it may be something I am doing wrong, and I am not sure how to fix it

Omnisharp seems to be running correctly, but upon starting atom and opening a CS file inside the solution nothing happens. If I try to restart the server, I then get the same error message.

I think this is because there actually is no server connected at the time of trying to restart it, but I do have the server installed, and OmniSharp.exe is actually on the path when atom starts.

1. Start Omnisharp server
2. Open file from project in atom (at this point atom does not say it is connected to omnisharp)
3. restart server through atom

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: linux 4.8.10-1-ARCH
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.7


### Stack Trace

Uncaught TypeError: Cannot read property 'state' of undefined

```
At /home/lief/.atom/packages/omnisharp-atom/dist/atom/solution-information.js:67

TypeError: Cannot read property 'state' of undefined
    at atom-workspace.<anonymous> (/home/lief/.atom/packages/omnisharp-atom/dist/atom/solution-information.js:67:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:02.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 omnisharp-atom:restart-server (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-go",
      "build-cargo",
      "builder-go",
      "go-config",
      "go-debug",
      "go-get",
      "go-plus",
      "godoc",
      "gofmt",
      "gometalinter-linter",
      "gorename",
      "language-erlang",
      "language-fish-shell",
      "language-rust",
      "linter-erlang",
      "linter-flake8",
      "linter-rust",
      "minimap",
      "minimap-linter",
      "navigator-go",
      "racer",
      "tester-go"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "sublime-default-syntax"
    ]
  },
  "omnisharp-atom": {
    "altGotoDefinition": true,
    "autoStartOnCompatibleFile": false,
    "codeLens": false,
    "enhancedHighlighting": true,
    "enhancedHighlighting19": false
  }
}
```

### Installed Packages

```coffee
# User
2-dark-syntax, v0.1.1 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (active)
atomic-emacs, v0.9.2 (inactive)
autocomplete-go, v1.3.0 (inactive)
build-cargo, v1.0.0 (inactive)
builder-go, v1.0.1 (inactive)
go-config, v1.2.4 (inactive)
go-debug, v0.1.22 (inactive)
go-get, v2.1.1 (inactive)
go-plus, v4.3.2 (inactive)
godoc, v1.1.1 (inactive)
gofmt, v1.2.0 (inactive)
gometalinter-linter, v1.2.2 (inactive)
gorename, v1.1.0 (inactive)
language-erlang, v3.0.0 (inactive)
language-fish-shell, v1.0.5 (inactive)
language-rust, v0.4.8 (inactive)
linter, v1.11.18 (active)
linter-erlang, v0.3.1 (inactive)
linter-flake8, v2.1.1 (inactive)
linter-rust, v0.7.1 (inactive)
minimap, v4.25.6 (inactive)
minimap-linter, v1.6.0 (inactive)
navigator-go, v1.1.3 (inactive)
omnisharp-atom, v0.30.7 (active)
racer, v0.20.0 (inactive)
remove-all-keybindings, v0.2.0 (active)
sublime-default-syntax, v0.2.7 (active)
tester-go, v2.0.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```



Is there a path I need to set for omnisharp-atom to be able to find the server? I couldn't find anything of the like inside the omnisharp-atom settings.

OS: Arch-Linux
OmniSharp version: 1.9.beta19
dotnet-cli version: 1.0.0_preview2_003131
libuv version: 1.10.1
mono version: 4.6.1.3

**Comment by quasiblob** [comment] 2018-01-16 20:52
It's 2018 and I'm getting the same error with

Atom 1.23.3 x64 Windows 10 Pro x64
OmniSharp-atom 0.31.2

Would be nice to get omnisharp working, would like to try Unity + C# with it, as they are getting rid of MonoDevelop as IDE.
