### ISSUE TITLE
Yosemite 10.10.4 mono 3.12.1 not work

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-atom#328] opened 2015-05-22 05:57 UTC
On my Unity 3d project,No any errot tips or completition tips.And go to declaration also not working.
Atom verison is 0.201.0

**Comment by nosami** [comment] 2015-05-22 05:58
Duplicate of https://github.com/OmniSharp/omnisharp-atom/issues/325

**Comment by nosami** [comment] 2015-05-22 11:13
Should be fixed in v0.6.5

**Closed** 2015-05-22 17:13 UTC
