### ISSUE TITLE
Uncaught TypeError: this.editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by blake2002** [OmniSharp/omnisharp-atom#533] opened 2015-10-09 11:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.14

### Stack Trace

Uncaught TypeError: this.editor.displayBuffer.getScrollTop is not a function

```
At C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71

TypeError: this.editor.displayBuffer.getScrollTop is not a function
    at Tooltip.pixelPositionFromMouseEvent (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lookup.js:183:42)
    at C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lookup.js:58:33
    at tryCatcher (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at InnerObserver.onNext (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4790:43)
    at InnerObserver.tryCatcher (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
    at Subject.tryCatcher (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at AutoDetachObserver.tryCatcher (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at HTMLDivElement.handler (C:\Users\llqiu.leo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:379:9)
```

### Commands

```
     -0:19.4.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "atom-sharp"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
color-picker, v2.0.11
json-schema, v0.1.15
linter, v1.8.1
omnisharp-atom, v0.24.14
you-complete-me, v0.6.3

# Dev
No dev packages
```

**Comment by Jalict** [comment] 2015-10-30 10:00
[Enter steps to reproduce below:]
1. Opened Atom using Unity3D (Build #2015091501) by pressing the "Sync MonoDevelop Project" in Assets.
2. Open one of my .cs scripts (Completely fresh file)
3. Error occurs

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.9


### Stack Trace

Uncaught TypeError: this.editor.displayBuffer.getScrollTop is not a function

```
At /home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

TypeError: this.editor.displayBuffer.getScrollTop is not a function
    at Tooltip.pixelPositionFromMouseEvent (/home/jalict/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:183:42)
    at /home/jalict/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:58:33
    at tryCatcher (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5281:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.tryCatcher (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at Subject.Rx.Subject.addProperties.onNext (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5908:19)
    at Subject.tryCatcher (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at AutoDetachObserver.tryCatcher (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at HTMLDivElement.handler (/home/jalict/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:422:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/jalict/Projects/"
  },
  "omnisharp-atom": {
    "codeLens": false,
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.9.1
omnisharp-atom, v0.25.9

# Dev
No dev packages
```

**Comment by Jalict** [comment] 2015-10-30 10:16
After a bit of testing it seems to happen every time I open a file or Atom gets opened.

**Comment by david-driscoll** [comment] 2015-10-30 10:50
It's from the latest atom, I published a patch for it last night. Let me
know if it's still happening after updating.

On Fri, Oct 30, 2015 at 6:16 AM Frans Larsen <notifications@github.com>
wrote:

> After a bit of testing it seems to happen every time I open a file or Atom
> gets opened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OmniSharp/omnisharp-atom/issues/533#issuecomment-152483118>
> .
>
-- 
Thanks,
David

**Comment by Jalict** [comment] 2015-11-07 14:35
Seems to be fixed now, thanks!

**Closed** 2015-12-05 21:11 UTC
