### ISSUE TITLE
Utf-8 with BOM get an error tips

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-atom#244] opened 2015-05-11 03:14 UTC
![qq20150511-1 2x](https://cloud.githubusercontent.com/assets/1423545/7558017/321b3a44-f7ce-11e4-96ca-77a4c956cddd.png)

Please support UTF-8 with BOM file.Thanks

**Comment by nosami** [comment] 2015-05-11 03:17
Closing. Duplicate of #165

**Closed by nosami** 2015-05-11 03:17 UTC
