### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by hmemcpy** [OmniSharp/omnisharp-atom#309] opened 2015-05-18 12:29 UTC
[Enter steps to reproduce below:]

See #308 - I got this error as well.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.33

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:80

TypeError: Cannot read property '0' of undefined
  at ClientManager.getClientForEditor (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:80:75)
  at ClientManager.getClientForActiveEditor (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:67:25)
  at Function.Object.defineProperty.get [as client] (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:31:28)
  at GoToDefinition.underlineIfNavigable (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:91:17)
  at C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:47:79

```

### Commands

```
  4x -1:28.4.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autoclose-html, v0.16.0
browser-refresh, v0.8.3
git-plus, vundefined
language-spec, v0.1.0
linter, v0.12.2
monokai, v0.14.0
omnisharp-atom, v0.4.33
open-in-browser, vundefined
spec-maker, v0.4.0

# Dev
settings-view, v0.185.0
```

**Comment by nosami** [comment] 2015-05-19 04:23
Should be fixed in v0.5.0. Please re-open if it isn't!

**Comment by willl** [comment] 2015-05-21 23:59
I'm getting the same error with 0.6.2.

[Enter steps to reproduce below:]

1. Open a valid C# file that will kick off OmniSharp
2. Create a new file.
3. Paste some random (incomplete) C# code that you'd like to have syntax highlighting for
Eg: `((model.Type == "A") || (model.Type == "B"))`
4. Change the grammar to C#.
5. BAM! `Uncaught TypeError: Cannot read property '0' of undefined`. 

**Atom Version**: 0.200.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.6.2


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\william\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:129

TypeError: Cannot read property '0' of undefined
  at ClientManager.getClientForEditor (C:\Users\william\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:129:88)
  at LinterCSharp.lintFile (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\linter.js:43:14)
  at C:\Users\william\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\william\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:35.5.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:22.4.0 omnisharp-atom:toggle-output (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -0:09.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:05.5.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:05.3.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:05.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:04.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:04.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:delete (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".suo",
      ".vsmdi",
      ".vscc",
      ".dll"
    ],
    "disabledPackages": [
      "data-atom",
      "emmet",
      "wrap-guide",
      "js-refactor",
      "refactor"
    ],
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autoclose-html, v0.16.0
highlight-selected, v0.9.3
language-aspx, v0.4.0
language-csharp, v0.5.0
language-cshtml, v0.1.1
language-powershell, v2.0.1
language-sln, v0.1.0
language-vbdotnet, v0.1.0
linter, v0.12.6
monokai, v0.14.0
omnisharp-atom, v0.6.2
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by nosami** [comment] 2015-05-22 17:15
@david-driscoll this is an interesting issue. We can't deal with files that don't have a filename as we don't know which project/client to associate them with.

**Comment by nosami** [comment] 2015-05-22 17:49
My gut feeling is that we should somehow force the user to select a file name for new files.

**Comment by nosami** [comment] 2015-05-22 18:30
https://atom.io/packages/fancy-new-file seems like a good candidate for implementing new file behaviour.  When creating new files in both vim and emacs, the filename is specified up front.

**Comment by david-driscoll** [comment] 2015-05-30 03:38
Looks like it's complaining about this line: https://github.com/OmniSharp/omnisharp-atom/blob/v0.4.33/lib/omni-sharp-server/client-manager.ts#L109

I just tried to get this to happen locally, no dice (And I already had markdown preview installed!).  There have been a bunch of new guards added in the latest version, @hmemcpy would you have a chance to try it again with the latest and let us know if it's still happening for you?

**Closed** 2015-07-11 23:54 UTC
