### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by brendanjerwin** [OmniSharp/omnisharp-atom#455] opened 2015-07-29 12:30 UTC
Was opening a fairly large project for the first time. The nugget restore was running. Closed the notification, then clicked the pulsating "flame logo" to see how it was going. Clicked it again once or twice, toggling the dock open and closed, and the error popped up.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.11
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.22.6

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At /Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactMount.js:730

TypeError: Cannot read property 'firstChild' of undefined
  at Object.ReactMount.findComponentRoot (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactMount.js:730:39)
  at Object.ReactMount.findReactNodeByID (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactMount.js:676:23)
  at Object.getNode (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactMount.js:147:32)
  at Object.executeDispatch (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:109:41)
  at SimpleEventPlugin.executeDispatch (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:46:22)
  at Array.forEach (native)
  at forEachAccumulated (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
  at Object.EventPluginHub.processEventQueue (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:253:5)
  at runEventQueueInBatch (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:110:20)
  at ReactEventListener.dispatchEvent (/Users/brendanjerwin/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventListener.js:174:20)

```

### Commands

```
     -0:48.8.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:11.7.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ex-mode"
    ]
  },
  "omnisharp-atom": {
    "autoAdjustTreeView": true,
    "enhancedHighlighting": true,
    "useAdvancedFileNew": true,
    "useLeftLabelColumnForSuggestions": true,
    "showDiagnosticsForAllSolutions": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.7.0
file-icon-supplement, v0.8.3
file-icons, v1.5.8
indent-guide-ext, v0.2.1
inline-messenger, v1.2.7
json-schema, v0.1.10
language-docker, v1.1.3
language-systemd, v0.1.0
make-executable, v0.1.1
minimap, v4.12.1
omnisharp-atom, v0.22.6
pigments, v0.9.2
relative-line-numbers, v0.1.5
tree-view-git-branch, v0.0.2
tree-view-git-status, v0.1.2
vim-mode, v0.57.0
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by brendanjerwin** [comment] 2015-07-29 12:31
Interesting, now it seems to do it whenever I click the flame logo.

**Comment by brendanjerwin** [comment] 2015-07-30 11:46
Even in smaller projects this seems to happen. Recently its been when _closing_ the dock.

**Comment by brendanjerwin** [comment] 2015-07-30 12:10
Ah ha! It appears to be a conflict with the Omnisharp/json-schema package. Install/enable that package and restart Atom. Then this starts happening.

**Comment by melcloud** [comment] 2015-08-06 00:20
Same thing here for Windows.

**Comment by david-driscoll** [comment] 2015-08-06 01:34
I'll look into this.

**Comment by mvhoute** [comment] 2015-08-06 09:27
+1

**Comment by david-driscoll** [comment] 2015-08-10 01:44
@brendanjerwin @melcloud trying to mess with it right now and I can't seem to get it throw.

right now I'm just mess with package restore through a project.json file, closing the notification and opening/closing the output/flame.

Any other tips, or ways that you've seen it triggered?

**Comment by brendanjerwin** [comment] 2015-08-10 02:04
@david-driscoll I was able to get it to happen again, on a brand new machine, by installing json-schema and opening a fresh `yo aspnet` console project with `atom .`.

It did not happen after installing json-schema without opening a project.

After loading the project, I saw that it did all the stuff it does: "1 Projects", etc. And now it tosses this exception whenever anything omnisharp-related is clicked. 

Uninstalling json-schema and restarting atom in the same project lets it work correctly.

**Comment by melcloud** [comment] 2015-08-11 07:34
+1 for @brendanjerwin. Same problem here. Only happens on windows 7 for me. My surface pro running windows 10 works fine.

**Comment by melcloud** [comment] 2015-08-11 12:53
I can replicate on my windows 10 now. I use:

- dnx clr 1.0.0-beta6 x64

seems to happen after open `project.json` file

**Comment by david-driscoll** [comment] 2015-08-12 01:19
@melcloud @brendanjerwin  Checkout the latest builds of omnisharp atom and json-schema, let me know if this issue is still happening.  I have fixed an odd exception with json schema in json files, perhaps that was the root cause.

**Comment by melcloud** [comment] 2015-08-12 12:56
works fine for me now.  Thanks

**Comment by brendanjerwin** [comment] 2015-08-12 23:39
Same here. Seems fine with both packages installed.

**Comment by david-driscoll** [comment] 2015-08-13 18:18
Awesome!  Thanks for the report.

**Closed by david-driscoll** 2015-08-13 18:18 UTC
