### ISSUE TITLE
Failed to activate the omnisharp-atom package

### ISSUE THREAD

**Issue by CarterWilde** [OmniSharp/omnisharp-atom#1023] opened 2018-04-07 01:46 UTC
1. Start atom

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2

### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:508:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9334:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.25.1/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.25.1/resources/app/src/config.js:862:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.25.1/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.25.1/resources/app/src/atom-environment.js:867:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-dark-minimal-ui 0.5.8 
atom-ide-ui 0.9.4 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
file-icons 2.1.18 
highlight-selected 0.13.1 
ide-csharp 0.6.2 
ide-json 0.2.1 
intentions 1.1.5 
language-cshtml 0.3.0 
language-sqf 0.3.0 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.8.1 
sass-autocompile 0.13.5 
teletype 0.12.0 
```

**Comment by tomuxmon** [comment] 2018-04-09 19:57
same here on ubuntu 16.04:

`TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/home/tomuxmon/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/home/tomuxmon/.atom/packages/omnisharp-atom/node_modules/lodash/lodash.js:508:11)
    at forEach (/home/tomuxmon/.atom/packages/omnisharp-atom/node_modules/lodash/lodash.js:9334:14)
    at OmniSharpAtom.activate (/home/tomuxmon/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)`

**Comment by hoaihuongbk** [comment] 2018-04-11 04:03
Same for Ubuntu 17.10

**Comment by dweslynch** [comment] 2018-04-12 00:07
Same here, also win10, same version of everything - only non-core package is teletype

**Comment by CarterWilde** [comment] 2018-04-12 00:10
What build of windows are you on? I'm on build 16299 (Version 10.0.16299)

**Comment by maellacour** [comment] 2018-04-17 12:52
Same for me on Ubuntu 16.04 as well. 
```
**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2

Failed to activate the omnisharp-atom package
```
I got the same stack trace as tomuxmon, so i don't repaste it.

**Comment by ArnaudValensi** [comment] 2018-04-19 19:50
Same for me on OSX.

**Comment by Maximegau** [comment] 2018-04-20 20:42
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:508:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9334:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:280:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
  3x -1:14.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
lazy-unity-helper 0.1.0 
omnisharp-atom 0.31.2 
teletype 0.12.1 
```

**Comment by maellacour** [comment] 2018-04-24 14:33
Same issue as #1020

**Comment by tqtran7** [comment] 2018-04-29 12:16
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (<embedded>:72542:33)
    at measure (<embedded>:72518:33)
    at Package.measure (<embedded>:72400:25)
    at activationPromise.Promise (<embedded>:72512:20)
    at Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:72510:38)
    at PackageManager.activatePackage (<embedded>:25755:42)
    at <embedded>:56239:35
    at exit (<embedded>:55876:22)
    at triggerExitCallback (<embedded>:130424:15)
    at ChildProcess.process.on (<embedded>:130454:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
     -3:48.4.0 application:add-project-folder (div.tool-panel.tree-view)
     -3:13.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.0.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.8.1 
todo-show 2.1.0 
```

**Comment by doctorgicu** [comment] 2018-05-02 00:27
same here on: Linux Mint 18.3 Sylvia 64-bit

After installation i got:

atom.grammars.startIdForScope is not a function
Hide Stack Trace
TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/home/giuseppe/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/home/giuseppe/.atom/packages/atom-beautify/node_modules/lodash/lodash.js:516:11)
    at forEach (/home/giuseppe/.atom/packages/atom-beautify/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/home/giuseppe/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)

**Comment by maellacour** [comment] 2018-05-02 07:25
Solved thanks to @koxu1996 and @Skehmatics in #1020. Solution also posted in #1025.
Code :

replace l.140 by : var grammars = atom.grammars.textmateRegistry || atom.grammars;
and l.145 by : grammars.startIdForScope(grammar.scopeName);

**Comment by bgattet** [comment] 2018-06-13 20:04
is the fix in ? It still does it for me

**Comment by CarterWilde** [comment] 2018-06-14 22:24
No, it still does it for me also.

**Comment by brundonsmith** [comment] 2018-06-16 00:13
Same here, Windows 10

**Comment by NullVoxPopuli** [comment] 2018-06-21 16:31
Same here: error still present, Ubuntu 18.04

**Comment by gslaughl** [comment] 2018-07-06 13:45
Same, Sierra 10.12.6

**Comment by takochako** [comment] 2018-07-09 21:07
Same. Windows 10, version 1709, build 16299.492. I don't know if it will be fixed though. The Omnisharp-Atom project looks like it's been abandoned since it's been over a year since the last release.

**Comment by CarterWilde** [comment] 2018-07-10 14:35
@takochako I looks like they have abandoned this project. The same thing happened with 
omnisharp-sublime. The only one they still support seems to be omnisharp-vscode.

**Comment by lsalomon** [comment] 2018-07-31 10:05
Solved intalling dotnet from microsoft offical [download page](https://www.microsoft.com/net/download) for osx. I think the problem was from installing dotnet from brew.

No more segfaults !!!!!!

Hope this will help !

**Comment by SierraKoda** [comment] 2018-08-28 20:53
@Eyap53 gave y'all the info. Will vouche. Works now after edit ~Parrot OS [Mate Structure]

**Comment by LloydNicholson** [comment] 2018-09-19 11:34
Still doesn't work for me on MacOS.

**Comment by bratfizyk** [comment] 2018-09-29 22:40
+1, Ubuntu 18.04

**Comment by ro-tex** [comment] 2018-10-06 11:12
I used the solution by @Eyap53 with one addition.

Original solution:
Find `omnisharp-atom.js` in your ~/.atom dir and change line 140
from `var grammars = atom.grammars;`
to `var grammars = atom.grammars.textmateRegistry || atom.grammars;`.

Addition:
Change line 145 
from `atom.grammars.startIdForScope(grammar.scopeName);` 
to `grammars.startIdForScope(grammar.scopeName);`
Change line 154
from `this.disposable.add(atom.grammars.onDidAddGrammar(grammarCb));`
to `this.disposable.add(grammars.onDidAddGrammar(grammarCb));`

**Comment by zral0kh** [comment] 2018-10-25 19:27
I still have the issue: `Arguments to CompositeDisposable.add must have a .dispose() method`
This is the console:
```TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1189015)
    at CompositeDisposable.add (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1189983)
    at Object.consumeProvider (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:161428)
    at Object.consumeProvider_2 (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:161126)
    at Provider.t.exports.Provider.provide (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:14:1034504)
    at ServiceHub.t.exports.ServiceHub.provide (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3024478)
    at Package.activateServices (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3032664)
    at Package.activateNow (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3029719)
    at measure (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3029043)
    at Package.measure (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3026674)
    at activationPromise.activationPromise.Promise (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3028903)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3028846)
    at PackageManager.activatePackage (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:378471)
    at n.forEach.e (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:373705)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:373689)
    at emitter.on (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:331211)
    at Function.simpleDispatch (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1185469)
    at Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:1186910)
    at Config.emitChangeEvent (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:333699)
    at Config.setRawValue (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:330939)
    at Config.set (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:326733)
    at Config.removeAtKeyPath (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:328756)
    at Package.enable (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:3026459)
    at PackageManager.enablePackage (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11:371403)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\user\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:14:2933579)```

Does anyone know hot to solve this?

**Comment by FlamingQaz** [comment] 2019-01-03 05:36
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/atom-drawio/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/atom-drawio/node_modules/lodash/lodash.js:9344:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3029561)
    at measure (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3028973)
    at Package.measure (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3026604)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3028833)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3028776)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:382657)
    at n.forEach.e (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:377891)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:377875)
    at emitter.on (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:335397)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1192200)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:337885)
    at Config.setRawValue (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:335125)
    at Config.set (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:330919)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:332942)
    at Package.enable (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3026389)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:375589)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:2935048)
```

### Commands

```
     -1:48.2.0 core:backspace (input.hidden-input)
     -1:40.8.0 core:undo (input.hidden-input)
     -1:39.7.0 core:save-as (input.hidden-input)
     -1:00.1.0 core:backspace (input.hidden-input)
     -0:57.9.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```
atom-drawio 1.13.0 
auto-save-on-idle 1.2.1 
bloodshot-ui 0.1.2 
dragon-fire-syntax 0.5.3 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
language-unityscript 0.37.0 
omnisharp-atom 0.31.2 
teletype 0.13.3 
unity-shader-files 0.3.1 
```

**Closed as completed** 2019-02-28 15:58 UTC
